"""Обновил дефолтный тип editDatе в начальное состояние

Revision ID: 36bd62c47ca5
Revises: 67cfd20f167f
Create Date: 2022-06-21 19:07:37.034303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bd62c47ca5'
down_revision = '67cfd20f167f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
