"""Обновил дефолтный тип editedDate

Revision ID: 97211b64723f
Revises: 38a4d58fa07f
Create Date: 2022-06-21 18:45:25.336424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97211b64723f'
down_revision = '38a4d58fa07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
