"""Обновил дефолтный тип editDatе

Revision ID: f4cdf15f954f
Revises: 97211b64723f
Create Date: 2022-06-21 18:48:08.164702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cdf15f954f'
down_revision = '97211b64723f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
