version: "3.6"
services:
  postgres:
    image: postgres:14.2
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    env_file:
      - .env

  redis:
    restart: always
    image: redis:6.2-alpine
    ports:
        - "${REDIS_PORT:-6379}:6379"